filters:
  - filter_type: file
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: roda-ui/roda-wui/src/main/resources/config/i18n/ServerMessages.properties
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/i18n/client/ClientMessages_<lang>.properties
  - filter_type: file
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: roda-ui/roda-wui/src/main/resources/config/i18n/client/ClientMessages.properties
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/i18n/client/ClientMessages_<lang>.properties
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Pre_Ingest.md
    source_language: en
    translation_files_expression: documentation/Pre_Ingest_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Advanced_Search.md
    source_language: en
    translation_files_expression: documentation/Advanced_Search_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/FAQ.md
    source_language: en
    translation_files_expression: documentation/FAQ_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Overview.md
    source_language: en
    translation_files_expression: documentation/Overview_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Troubleshooting.md
    source_language: en
    translation_files_expression: documentation/Troubleshooting_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Installation_Production_Environments.md
    source_language: en
    translation_files_expression: documentation/Installation_Production_Environments_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Developers_Guide.md
    source_language: en
    translation_files_expression: documentation/Developers_Guide_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Community_Support.md
    source_language: en
    translation_files_expression: documentation/Community_Support_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Representation_Information.md
    source_language: en
    translation_files_expression: documentation/Representation_Information_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Format_Normalization_Policy.md
    source_language: en
    translation_files_expression: documentation/Format_Normalization_Policy_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/EditDescriptiveMetadata.md
    source_language: en
    translation_files_expression: documentation/EditDescriptiveMetadata_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/README.md
    source_language: en
    translation_files_expression: documentation/README_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Quickstart.md
    source_language: en
    translation_files_expression: documentation/Quickstart_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Installation_Testing_Environments.md
    source_language: en
    translation_files_expression: documentation/Installation_Testing_Environments_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Documentation_Guide.md
    source_language: en
    translation_files_expression: documentation/Documentation_Guide_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Acknowledgements.md
    source_language: en
    translation_files_expression: documentation/Acknowledgements_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Statistics.md
    source_language: en
    translation_files_expression: documentation/Statistics_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Risk_Assessment.md
    source_language: en
    translation_files_expression: documentation/Risk_Assessment_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/License.md
    source_language: en
    translation_files_expression: documentation/License_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Translation_Guide.md
    source_language: en
    translation_files_expression: documentation/Translation_Guide_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Professional_Support.md
    source_language: en
    translation_files_expression: documentation/Professional_Support_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Metadata_Formats.md
    source_language: en
    translation_files_expression: documentation/Metadata_Formats_<lang>.md
  - filter_type: file
    file_format: GITHUBMARKDOWN
    source_file: documentation/Central_Authentication_Service.md
    source_language: en
    translation_files_expression: documentation/Central_Authentication_Service_<lang>.md
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/NotificationDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/NotificationDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/BrowseDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/BrowseDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/EditPermissionsDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/EditPermissionsDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/CookiesPolicy.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/CookiesPolicy_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/PreDisseminationsPortal.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/PreDisseminationsPortal_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/RIRelationsDescriptionWithWeb.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/RIRelationsDescriptionWithWeb_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/WelcomePortal.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/WelcomePortal_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/DisposalDestroyedRecordsDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/DisposalDestroyedRecordsDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/PreChildrenPortal.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/PreChildrenPortal_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/RIRelationsWithIntellectualEntity.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/RIRelationsWithIntellectualEntity_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/IngestProcessDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/IngestProcessDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/RiskIncidenceRegisterDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/RiskIncidenceRegisterDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/RIAssociationsDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/RIAssociationsDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/EditRiskIncidenceDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/EditRiskIncidenceDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/RiskRegisterDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/RiskRegisterDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/DisposalPolicyDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/DisposalPolicyDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/RIRelationsDescriptionHelp.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/RIRelationsDescriptionHelp_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/Error404.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/Error404_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/InternalProcessDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/InternalProcessDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/DisposalConfirmationDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/DisposalConfirmationDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/PreservationEventsDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/PreservationEventsDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/RIRelationsDescriptionWithText.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/RIRelationsDescriptionWithText_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/Publications.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/Publications_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/IngestAppraisalDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/IngestAppraisalDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/Statistics.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/Statistics_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/Banner.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/Banner_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/SearchDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/SearchDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/Error500.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/Error500_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/UserLogDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/UserLogDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/MissingRepresentationInformation.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/MissingRepresentationInformation_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/IngestTransferDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/IngestTransferDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/PreMetadataPortal.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/PreMetadataPortal_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/RIRelationsDescriptionWithRI.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/RIRelationsDescriptionWithRI_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/PreservationProcessDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/PreservationProcessDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/Footer.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/Footer_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/Welcome.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/Welcome_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/RepresentationInformationNetworkDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/RepresentationInformationNetworkDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/MemberManagementDescription.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/MemberManagementDescription_<lang>.html
  - filter_type: file
    file_format: HTML
    source_file: roda-ui/roda-wui/src/main/resources/config/theme/ErrorInactiveAccount.html
    source_language: en
    translation_files_expression: roda-ui/roda-wui/src/main/resources/config/theme/ErrorInactiveAccount_<lang>.html
