
CREATE USER 'guest'@'localhost';

GRANT ALL ON *.* TO 'RODAWUI_MYSQL_USER'@'localhost' IDENTIFIED BY 'RODAWUI_MYSQL_USER_PASSWD' WITH GRANT OPTION;
GRANT ALL ON *.* TO 'RODAWUI_MYSQL_USER'@'RODAWUI_HOST' IDENTIFIED BY 'RODAWUI_MYSQL_USER_PASSWD' WITH GRANT OPTION;
GRANT ALL ON *.* TO 'RODAWUI_MYSQL_USER'@'RODAMIGRATORLINUX_HOST' IDENTIFIED BY 'RODAWUI_MYSQL_USER_PASSWD' WITH GRANT OPTION;

