/**
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE file at the root of the source
 * tree and available online at
 *
 * https://github.com/keeps/roda
 */
package org.roda.core.data.v2.db.jobs;

import java.io.Serial;
import java.io.Serializable;
import java.util.Date;

import org.roda.core.data.v2.ip.AIPState;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * The report of a {@link Job} for one (source object, outcome object) pair
 * ({@code job_reports}).
 *
 * Its plugin steps are {@link JobReportStep}s. Steps completed, completion
 * percentage, plugin state, plugin details and last update are not stored:
 * they are derived from the steps when read.
 *
 * @author RODA Development Team
 */
@Entity
@Table(name = "job_reports")
public class JobReport implements Serializable {
  @Serial
  private static final long serialVersionUID = 1964413436823917046L;

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "pk")
  private Long pk;

  @Column(name = "job_id", nullable = false, columnDefinition = "uuid")
  private String jobId;

  @Column(name = "source_object_id", nullable = false)
  private String sourceObjectId;

  @Column(name = "source_object_class")
  private String sourceObjectClass;

  @Column(name = "source_object_original_name")
  private String sourceObjectOriginalName;

  @Column(name = "outcome_object_id", nullable = false)
  private String outcomeObjectId;

  @Column(name = "outcome_object_class")
  private String outcomeObjectClass;

  @Enumerated(EnumType.STRING)
  @Column(name = "outcome_object_state", length = 32)
  private AIPState outcomeObjectState;

  @Column(name = "plugin_id")
  private Integer pluginId;

  @Column(name = "total_steps", nullable = false)
  private int totalSteps;

  @Column(name = "title")
  private String title;

  @Column(name = "ingest_type", length = 64)
  private String ingestType;

  @Column(name = "transaction_id")
  private String transactionId;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "date_created", nullable = false)
  private Date dateCreated;

  // business id (jobId-sourceObjectId-outcomeObjectId), generated by the database: read-only here,
  // and only filled in once the row is read back from the database
  @Column(name = "id", insertable = false, updatable = false, columnDefinition = "text")
  private String id;

  public JobReport() {
    // used by JPA and serialization
  }

  public Long getPk() {
    return pk;
  }

  public void setPk(Long pk) {
    this.pk = pk;
  }

  public String getJobId() {
    return jobId;
  }

  public void setJobId(String jobId) {
    this.jobId = jobId;
  }

  public String getSourceObjectId() {
    return sourceObjectId;
  }

  public void setSourceObjectId(String sourceObjectId) {
    this.sourceObjectId = sourceObjectId;
  }

  public String getSourceObjectClass() {
    return sourceObjectClass;
  }

  public void setSourceObjectClass(String sourceObjectClass) {
    this.sourceObjectClass = sourceObjectClass;
  }

  public String getSourceObjectOriginalName() {
    return sourceObjectOriginalName;
  }

  public void setSourceObjectOriginalName(String sourceObjectOriginalName) {
    this.sourceObjectOriginalName = sourceObjectOriginalName;
  }

  public String getOutcomeObjectId() {
    return outcomeObjectId;
  }

  public void setOutcomeObjectId(String outcomeObjectId) {
    this.outcomeObjectId = outcomeObjectId;
  }

  public String getOutcomeObjectClass() {
    return outcomeObjectClass;
  }

  public void setOutcomeObjectClass(String outcomeObjectClass) {
    this.outcomeObjectClass = outcomeObjectClass;
  }

  public AIPState getOutcomeObjectState() {
    return outcomeObjectState;
  }

  public void setOutcomeObjectState(AIPState outcomeObjectState) {
    this.outcomeObjectState = outcomeObjectState;
  }

  public Integer getPluginId() {
    return pluginId;
  }

  public void setPluginId(Integer pluginId) {
    this.pluginId = pluginId;
  }

  public int getTotalSteps() {
    return totalSteps;
  }

  public void setTotalSteps(int totalSteps) {
    this.totalSteps = totalSteps;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getIngestType() {
    return ingestType;
  }

  public void setIngestType(String ingestType) {
    this.ingestType = ingestType;
  }

  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public Date getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(Date dateCreated) {
    this.dateCreated = dateCreated;
  }

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }
}
