--
-- Name: aip_entry_disposal_hold_ids; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.aip_entry_disposal_hold_ids (
                                                    aip_entry_id bigint NOT NULL,
                                                    hold_id character varying(255)
);


ALTER TABLE public.aip_entry_disposal_hold_ids OWNER TO admin;

--
-- Name: aip_entry_disposal_hold_trans_ids; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.aip_entry_disposal_hold_trans_ids (
                                                          aip_entry_id bigint NOT NULL,
                                                          hold_transitive_id character varying(255)
);


ALTER TABLE public.aip_entry_disposal_hold_trans_ids OWNER TO admin;

--
-- Name: disposal_confirmation_aip_entry; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.disposal_confirmation_aip_entry (
                                                        id bigint NOT NULL,
                                                        aip_collection character varying(255),
                                                        aip_creation_date timestamp(6) without time zone NOT NULL,
                                                        aip_disposal_schedule_id uuid NOT NULL,
                                                        aip_id uuid NOT NULL,
                                                        aip_level character varying(255) NOT NULL,
                                                        aip_number_of_files bigint NOT NULL,
                                                        aip_overdue_date timestamp(6) without time zone NOT NULL,
                                                        aip_size bigint NOT NULL,
                                                        aip_title character varying(255) NOT NULL,
                                                        created_at timestamp(6) without time zone NOT NULL,
                                                        destroyed_selection character varying(255) NOT NULL,
                                                        destroyed_transitive_source character varying(255),
                                                        job_id uuid NOT NULL,
                                                        parent_id uuid,
                                                        CONSTRAINT disposal_confirmation_aip_entry_destroyed_selection_check CHECK (((destroyed_selection)::text = ANY ((ARRAY['DIRECT'::character varying, 'TRANSITIVE'::character varying])::text[])))
);


ALTER TABLE public.disposal_confirmation_aip_entry OWNER TO admin;

--
-- Name: disposal_confirmation_aip_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.disposal_confirmation_aip_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.disposal_confirmation_aip_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: disposal_confirmations; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.disposal_confirmations (
                                               id bigint NOT NULL,
                                               created_at timestamp(6) without time zone NOT NULL,
                                               disposal_confirmation_id uuid NOT NULL,
                                               job_id uuid NOT NULL
);


ALTER TABLE public.disposal_confirmations OWNER TO admin;

--
-- Name: disposal_confirmations_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.disposal_confirmations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.disposal_confirmations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: disposal_confirmation_aip_entry disposal_confirmation_aip_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.disposal_confirmation_aip_entry
    ADD CONSTRAINT disposal_confirmation_aip_entry_pkey PRIMARY KEY (id);


--
-- Name: disposal_confirmations disposal_confirmations_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.disposal_confirmations
    ADD CONSTRAINT disposal_confirmations_pkey PRIMARY KEY (id);

--
-- Name: disposal_confirmations ukkel16i2fkr1ewkhx8ndriku28; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.disposal_confirmations
    ADD CONSTRAINT ukkel16i2fkr1ewkhx8ndriku28 UNIQUE (job_id);


--
-- Name: disposal_confirmations ukljmsphly9n1nerf0hqit88ur8; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.disposal_confirmations
    ADD CONSTRAINT ukljmsphly9n1nerf0hqit88ur8 UNIQUE (disposal_confirmation_id);

--
-- Name: aip_entry_disposal_hold_ids fketnlv8mdmtgfs6ny5jya15lf4; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.aip_entry_disposal_hold_ids
    ADD CONSTRAINT fketnlv8mdmtgfs6ny5jya15lf4 FOREIGN KEY (aip_entry_id) REFERENCES public.disposal_confirmation_aip_entry(id);


--
-- Name: aip_entry_disposal_hold_trans_ids fkhac30gmxqwcuxpbcix3gtnf7y; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.aip_entry_disposal_hold_trans_ids
    ADD CONSTRAINT fkhac30gmxqwcuxpbcix3gtnf7y FOREIGN KEY (aip_entry_id) REFERENCES public.disposal_confirmation_aip_entry(id);
